### ISSUE TITLE
TRAIN_FULL.md Part 3, Step 4: not in the list

### ISSUE THREAD

**Issue by takbess** [prannaykaul/lvc#13]
Following the instructions, I tried the command:
```
python -m tools.train_net_reg_qe \
    --config-file configs/COCO-detection/cascade_ubbr_R_50_FPN_ft_all_30shot_aug_ftmore.yaml \
    --num-gpus 2 \
    --opts \
    --resume \
    --eval-only \
    DATASETS.DT_PATH "('checkpoints/coco/faster_rcnn/faster_rcnn_R_50_FPN_ft_all_30shot_aug_ftmore_dropout/inference/coco_instances_trainval_results_score_max10_min08_full_all_dino_vits8_10_cosine.json',)" \
    MODEL.META_ARCHITECTURE "GeneralizedRCNNRegOnly" \
    QUERY_EXPAND.ENABLED True
```
The difference from the original command of Part 3, Step 4 in TRAIN_FULL.md is "--num-gpus 2".
Then, I got the following error:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.vscode-server/extensions/ms-python.python-2022.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/user/.vscode-server/extensions/ms-python.python-2022.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/user/.vscode-server/extensions/ms-python.python-2022.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "/home/user/.vscode-server/extensions/ms-python.python-2022.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/.vscode-server/extensions/ms-python.python-2022.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/misc/fazz-face/work/bessho/lvc/tools/train_net_reg_qe.py", line 275, in <module>
    launch(
  File "/misc/fazz-face/work/bessho/lvc/detectron2/engine/launch.py", line 55, in launch
    mp.spawn(
  File "/home/user/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/user/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/user/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:
 
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/misc/fazz-face/work/bessho/lvc/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/misc/fazz-face/work/bessho/lvc/tools/train_net_reg_qe.py", line 247, in main
    res = Trainer.test(cfg, model)
  File "/misc/fazz-face/work/bessho/lvc/tools/train_net_reg_qe.py", line 129, in test
    data_loader = cls.build_test_loader(cfg, dataset_name)
  File "/misc/fazz-face/work/bessho/lvc/tools/train_net_reg_qe.py", line 216, in build_test_loader
    return build_detection_test_loader(cfg, dataset_name, mapper=DatasetMapperIgnore(cfg,
  File "/misc/fazz-face/work/bessho/lvc/lvc/data/build.py", line 320, in build_detection_test_loader
    cfg.DATASETS.PROPOSAL_FILES_TEST[list(cfg.DATASETS.TEST).index(dataset_name)]
ValueError: 'checkpoints/coco/faster_rcnn/faster_rcnn_R_50_FPN_ft_all_30shot_aug_ftmore_dropout/inference/coco_instances_trainval_results_score_max10_min08_full_all_dino_vits8_10_cosine.json' is not in list
```
I failed to find how to solve this error ...
I’d appreciate your help.

**Comment by prannaykaul** [comment]
This needed the "MODEL.LOAD_PROPOSALS False" in the command line args. Please see the latest commit
