### ISSUE TITLE
'Non-existent config key: DATASETS.PROPOSALS_FILES_TRAIN'

### ISSUE THREAD

**Issue by int2char** [prannaykaul/lvc#6]
**cmd:**  CUDA_VISIBLE_DEVICES=0,1,2,3 python -m tools.train_net_reg     --config-file configs/COCO-detection/cascade_ubbr_R_50_FPN_base.yaml     --num-gpus 4

**config file** :
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "R-50.pkl"
  META_ARCHITECTURE: "GeneralizedRCNN"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "CascadeROIHeads"
    NUM_CLASSES: 13
    OUTPUT_LAYER: "BoxOnlyLayersCascade"
    PROPOSAL_APPEND_GT: False
    POSITIVE_FRACTION: 1.0
    BATCH_SIZE_PER_IMAGE: 64
    IOU_THRESHOLDS: [0.3,]
  ROI_BOX_HEAD:
    NUM_FC: 3
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_BOX_CASCADE_HEAD:
    IOUS: [0.3,0.5,0.7]
  BACKBONE:
    FREEZE_AT: 2
  PROPOSAL_GENERATOR:
    NAME: "RBG"
  LOAD_PROPOSALS: True
DATASETS:
  PROPOSALS_FILES_TRAIN: （"checkpoints/coco/faster_rcnn/faster_rcnn_R_50_FPN_base/inference/coco_proposals_trainval_results.pkl"，）
  PROPOSALS_FILES_TEST : （"checkpoints/coco/faster_rcnn/faster_rcnn_R_50_FPN_base/inference/coco_proposals_test_results.pkl"，）
  #TRAIN: ('coco_jichu',)
  #FS_TRAIN: ('coco_jichu',)
  #TEST: ('coco_train_nolabel',)
INPUT:
  CROP:
    ENABLED: True
    SIZE: [0.8, 0.8]
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (90000, 100000)
  MAX_ITER: 110000
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 1000
OUTPUT_DIR: "checkpoints/coco/cascade_ubbr/cascade_ubbr_R_50_FPN_base"

**erro:**
Traceback (most recent call last):
  File "/mnt2/zq/anaconda/envs/lvc/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/mnt2/zq/lvc/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/mnt2/zq/lvc/tools/train_net_reg.py", line 252, in main
    cfg = setup(args)
  File "/mnt2/zq/lvc/tools/train_net_reg.py", line 242, in setup
    cfg.merge_from_file(args.config_file)
  File "/mnt2/zq/lvc/detectron2/config/config.py", line 49, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/mnt2/zq/anaconda/envs/lvc/lib/python3.8/site-packages/fvcore/common/config.py", line 132, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/mnt2/zq/anaconda/envs/lvc/lib/python3.8/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/mnt2/zq/anaconda/envs/lvc/lib/python3.8/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/mnt2/zq/anaconda/envs/lvc/lib/python3.8/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: DATASETS.PROPOSALS_FILES_TRAIN'

**Comment by prannaykaul** [comment]
This should be resolved now with the latest commit.
